version: '3.9'

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5436:5432"
    volumes:
      - data:/var/lib/postgresql/kithli
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "5000:5020"
volumes:
  data: