databases:
  - name: kithli-db
    plan: free
    databaseName: kithli
    user: kithli_user

services:
  - name: kithli
    type: web
    runtime: go
    buildCommand: go build -o kithli .
    startCommand: ./kithli